# Generated by Django 4.1.4 on 2022-12-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='제목')),
                ('spend_cate', models.CharField(blank=True, choices=[('Expenditure', '지출'), ('Income', '수입')], max_length=11, verbose_name='소비종류')),
                ('money', models.IntegerField(verbose_name='금액')),
                ('spend_date', models.DateField(verbose_name='소비날짜')),
                ('bio', models.TextField(verbose_name='상세내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
            ],
        ),
    ]
