# Generated by Django 4.1.4 on 2022-12-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='제목')),
                ('money', models.BigIntegerField(verbose_name='사용한 돈')),
                ('bio', models.TextField(verbose_name='상세내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
            ],
        ),
    ]
