# Generated by Django 4.1.4 on 2022-12-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='상세내용'),
        ),
    ]
