# Generated by Django 4.1.4 on 2022-12-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=256)),
                ('shortner_url', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(verbose_name='생성날짜')),
            ],
        ),
    ]
