# Generated by Django 4.1.4 on 2022-12-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_urlshortner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshortner',
            name='shortner_url',
        ),
        migrations.AddField(
            model_name='urlshortner',
            name='shorten_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='urlshortner',
            name='original_url',
            field=models.URLField(max_length=256),
        ),
    ]
