# Generated by Django 4.1.4 on 2022-12-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_urlshortner_shortner_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성날짜'),
        ),
    ]
